# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iP47CWlC2SPVmDqDw57gNn8QCewxxDxT
"""

import streamlit as st
import pandas as pd
import joblib

st.set_page_config(page_title = 'Boston house price predictor',
                   page_icon = '🏠',)
model= joblib.load('model.pkl')


st.title('Boston house price predictor')
st.write('Enter your feature values to predict the house price in $1000s')

st.header("Input Features")

crim = st.number_input("CRIM - per capita crime rate by town", min_value=0.0, value=0.10, step=0.01)
Zn = st.number_input("ZN - residential land zoned over 25,000 sq.ft.", min_value=0.0, value=0.0, step=1.0)
indus = st.number_input("INDUS - non-retail business acres per town", min_value=0.0, value=8.0, step=0.1)
chas = st.selectbox("CHAS - tract bounds Charles River?", [0, 1])
Nox = st.number_input("NOX - nitric oxides concentration", min_value=0.0, value=0.50, step=0.01)
Rm = st.number_input("RM - average number of rooms per dwelling", min_value=0.0, value=6.0, step=0.1)
Age = st.number_input("AGE - proportion of old owner-occupied units", min_value=0.0, value=65.0, step=1.0)
Dis = st.number_input("DIS - distance to employment centres", min_value=0.0, value=4.0, step=0.1)
Rad = st.number_input("RAD - accessibility to radial highways", min_value=1, value=4, step=1)
Tax = st.number_input("TAX - property-tax rate per $10,000", min_value=0.0, value=300.0, step=1.0)
Ptratio = st.number_input("PTRATIO - pupil-teacher ratio", min_value=0.0, value=18.0, step=0.1)
B = st.number_input("B - calculated demographic feature", min_value=0.0, value=390.0, step=1.0)
Lstat = st.number_input("LSTAT - % lower status of the population", min_value=0.0, value=12.0, step=0.1)


input_data = pd.DataFrame({
    "crim": [crim],
    "Zn": [Zn],
    "indus": [indus],
    "chas": [chas],
    "Nox": [Nox],
    "Rm": [Rm],
    "Age": [Age],
    "Dis": [Dis],
    "Rad": [Rad],
    "Tax": [Tax],
    "PTRATIO": [Ptratio],
    "B": [B],
    "LSTAT": [Lstat]
})

if st.button('Predict House Price'):
  prediction= model.predict(input_data)
  st.success(f'The predicted house price is ${prediction[0]:.2f}')
