# -*- coding: utf-8 -*-
"""model.pk

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GkZ8C5R5mGsWRi9qIDi1ZHJVqVgRcEGT
"""

import pandas as pd
df = pd.read_csv("/content/boston.csv")
df.head()

from sklearn.linear_model import LinearRegression
import joblib
X = df.drop(columns = ['Medv'])
y= df['Medv']
model = LinearRegression()
model.fit(X,y)
joblib.dump(model, 'model.pkl')
print('model saved')

joblibload()